name: Publish Python Package to PyPI

on:
  release:
    types: [published]   # Trigger on GitHub release published event

permissions:
  contents: read         # Read repository contents
  id-token: write        # Needed for pypa/gh-action-pypi-publish authentication

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install build dependencies and build package
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pypi        # Use environment named pypi
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
        env:
          # The action uses this token to authenticate with PyPI
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
